version: "3.8"

services:
  s3store-create-bucket:
    image: minio/mc
    container_name: s3store-create-bucket
    depends_on:
      - s3store
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
    volumes:
      - './docker/s3:/etc/minio'
    entrypoint: /etc/minio/create_bucket.sh
